### ISSUE TITLE
class ArrayImpl has no to_py

### ISSUE THREAD

**Issue by bkhnk48** [StanfordASL/RiskAverseTrajOpt#2]
In your file car/driving.py, I got an error: ArrayImpl object has no attribute to_py. These errors are in line 396, 408, 520, 521, 558, 559
Idk for sure why the errors happened but I fix it by use np.array instead of to_py.
For example: p.to_py( ) becomes np.array(p).
Hope it could help someone.

**Comment by thomasjlew** [comment]
Thank you for pointing the fix to this error: I was using an older version of jax at the time (jax 0.2.11 and jaxlib 0.1.63). [to_py() is deprecated since jax 0.3.17](https://jax.readthedocs.io/en/latest/changelog.html).

Note that it is recommended to use `np.asarray(p) `instead of `np.array(p)` to avoid copying the array in memory, see https://github.com/google/jax/issues/1961#issuecomment-572306453.
